namespace TchiboFamilyCircle.Dto
{
    public enum FamilyMemberType
    {
        Husband,
        Wife,        
        Son,
        Dauther,
        Daddy,
        Mommy,
        Brother,
        Sister,       
        CousinMale,
        CousinFemale,
        FatherInLaw,
        MotherInLaw,      
        Boyfriend,
        Girlfriend,
        FriendMale,
        FriendFemale,      
        Nephew,
        Nice,
        Uncle,
        Aunt,
        Grandpa,
        Grandma,
        RelativeMale,
        RelativeFemale        
    }
}
